name: Scraper Workflow

on:
  schedule:
    # 毎日1回実行
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  scraper:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        pip install requests beautifulsoup4

    - name: Run scraper
      run: |
        python scraper.py

    - name: Commit and push results
      run: |
        git config --global user.name "Your Name"
        git config --global user.email "your-email@example.com"
        git add data.json
        git commit -m "Update data.json with new figure info"
        git push
